image: node:16.10.0

stages:
  - dev

deploy_dev:
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_DEV}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_DEV}
  script:
    - apt-get update
    - npm install -g serverless
    - serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
    - serverless deploy --stage dev
  only:
    - dev
